---
version: "3"
services:
  qbittorrent:
    image: ghcr.io/bradyslot/greedy-torrent:latest
    build:
      context: .
      args:
        - PUID=1000
        - PGID=1000
    hostname: greedy-torrent
    container_name: greedy-torrent
    volumes:
      - ~/srv/qBittorrent:/config
      - ~/Storage/Torrents:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
